### ISSUE TITLE
api: stabilise and document

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio-records-rest#99]
- [ ] check existing API functionality
  - [ ]  views: handle elasticsearch errors #84
  - [ ]  global: view configuration refactoring (blocker for release) #64
  - [ ]  views: html link in json serialization #46
  - [ ]  views: integrate API authentication/access control #14
- [ ] add missing important API functionality
- [ ] check API function signatures and parameters
- [x] enhance API docstrings (`param`, `returns`, `raises`, `versionadded`)
- [x] plug API functions to existing docs
- [x] add section about configuration of search class (#102)

**Comment by hachreak** [comment]
@jirikuncar @lnielsen do you think the first 3 points are fine? Or do we need to improve somehow the API?
